# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaCzS8fb3X2pyosl-1AegbUCBpzGli3p
"""

import streamlit as st
import pickle
from audiorecorder import audiorecorder
import whisper
from rapidfuzz import fuzz, process
from pydub import AudioSegment
import os

st.set_page_config(
    page_title="Identifikasi Ayat Quran",
    page_icon="📖",
    layout="centered"
)

st.title("📖 Identifikasi Ayat Al-Qur’an dari Audio")

# Load objek dari pickle kamu
DATA_PATH = "stream.pkl"

@st.cache_data
def load_data_pickle():
    data = pickle.load(open(DATA_PATH,'rb'))
    return data

data_pickle = load_data_pickle()

# Asumsi struktur dari pickle
verses = data_pickle.get("verses", [])
mapping = data_pickle.get("mapping", {})

# Load Whisper model
@st.cache_resource
def load_whisper_model():
    return whisper.load_model("base")

model = load_whisper_model()

def convert_audio(audio_file):
    if audio_file.endswith(".mp3"):
        sound = AudioSegment.from_mp3(audio_file)
        wav_file = "audio_temp.wav"
        sound.export(wav_file, format="wav")
        return wav_file
    return audio_file

def transcribe_audio(audio_file):
    audio_file = convert_audio(audio_file)
    result = model.transcribe(audio_file, language="id")
    return result["text"]

def identify_verse(teks):
    if not verses:
        return None

    match = process.extractOne(
        teks,
        verses,
        scorer=fuzz.ratio
    )

    if match:
        best_text = match[0]
        score = match[1]
        ayat = mapping.get(best_text)

        if ayat:
            return {
                "score": score,
                "surat": ayat["namaLatin"],
                "nomorAyat": ayat["nomorAyat"],
                "arab": ayat["teksArab"],
                "terjemahan": ayat["teksIndonesia"]
            }

    return None


# Pilihan input audio
option = st.radio(
    "Pilih Metode Input:",
    ["Upload Audio", "Rekam Langsung"]
)

audio_file = None

if option == "Upload Audio":
    uploaded = st.file_uploader(
        "Upload audio ayat:",
        type=["mp3","wav"]
    )

    if uploaded:
        with open(uploaded.name,'wb') as f:
            f.write(uploaded.getbuffer())

        audio_file = uploaded.name
        st.audio(audio_file)

else:
    st.write("🎤 Rekam suara Anda:")
    audio = audiorecorder("Mulai Rekam","Stop Rekam")

    if len(audio) > 0:
        audio.export("rekaman_user.wav", format="wav")
        audio_file = "rekaman_user.wav"
        st.audio(audio_file)


# Tombol proses identifikasi
if st.button("Identifikasi Ayat") and audio_file:
    with st.spinner("Memproses..."):
        teks = transcribe_audio(audio_file)

        st.subheader("Hasil Transkripsi:")
        st.write(teks)

        hasil = identify_verse(teks)

        if hasil:
            st.success("Ayat berhasil diidentifikasi!")

            st.subheader("Detail Ayat")

            st.write(f"**Surat:** {hasil['surat']}")
            st.write(f"**Nomor Ayat:** {hasil['nomorAyat']}")
            st.write(f"**Kemiripan:** {hasil['score']}%")

            st.subheader("Teks Arab:")
            st.write(hasil["arab"])

            st.subheader("Terjemahan:")
            st.write(hasil["terjemahan"])

        else:
            st.error("Ayat tidak dapat dikenali")

# Hapus file sementara setelah proses
if audio_file and audio_file not in ["rekaman_user.wav"]:
    try:
        os.remove(audio_file)
    except:
        pass